r0[ipv6]=true
r0[0]=net0
r0[1]=net1

r1[bridged]=true
r1[ipv6]=true
r1[0]=net1
r1[1]=net2

pca1[0]=net0
pca1[ipv6]=true

pca2[0]=net0
pca2[ipv6]=true

pcb1[0]=net1
pcb1[ipv6]=true

pcc1[0]=net2
pcc1[ipv6]=true

pcc2[0]=net2
pcc2[ipv6]=true
