CREATE TABLE JOUEUR (
	idJoueur INT PRIMARY KEY,
	nom VARCHAR(30) NOT NULL,
	age SMALLINT NULL,
	nationalite VARCHAR(30) NULL
)

CREATE TABLE JEUX (
	idJeux INT PRIMARY KEY,
	titre VARCHAR(30) NOT NULL,
	version VARCHAR(30) NULL
)

CREATE TABLE PARTIE (
	idJoueur INT FOREIGN KEY REFERENCES JOUEUR(idJoueur) NOT NULL,
	idJeux INT FOREIGN KEY REFERENCES JEUX(idJeux) NOT NULL,
	datePartie DATE NULL,
	score INT NULL
)

CREATE TABLE TOPSCORE (
	idJoueur INT FOREIGN KEY REFERENCES JOUEUR(idJoueur) NOT NULL,
	idJeux INT FOREIGN KEY REFERENCES JEUX(idJeux) NOT NULL,
	scoreMAX INT NULL,
	PRIMARY KEY (idJoueur, idJeux)
)

